version: '3.3'

services:
  db-node-1:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    image: mariadb:hl
    container_name: db-node-1
    restart: unless-stopped
    # security_opt:
    #   - seccomp=unconfined
    environment:
      MYSQL_DATABASE: hl
      MYSQL_USER: postgres
      MYSQL_PASSWORD: postgres
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    # networks:
    #   - mai-network
    ports:
      - 3360:3306
    volumes:
      - db-node-1-data:/var/lib/mysql

  db-node-2:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    image: mariadb:hl
    container_name: db-node-2
    # security_opt:
    #   - seccomp=unconfined
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: hl
      MYSQL_USER: postgres
      MYSQL_PASSWORD: postgres
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    # networks:
    #   - mai-network
    ports:
      - 3361:3306
    volumes:
      - db-node-2-data:/var/lib/mysql

  proxysql:
    build:
      context: docker/proxysql
      dockerfile: Dockerfile
    image: proxysql:hl
    container_name: proxysql
    depends_on:
      - "db-node-1"
      - "db-node-2"
    # command: >
    #   --initial
    volumes:
      - proxysql-data:/var/lib/proxysql
      # - ./docker/proxysql/proxysql.cnf:/etc/proxysql.cnf
    # networks:
    #   - mai-network
    ports:
      # Mysql Client Port
      - "6033:6033"
      # Mysql Admin Port
      - "6032:6032"
    healthcheck:
      test: "/usr/bin/mysql -h 127.0.0.1 -P 6033 --user=postgres --password=postgres --execute \"SHOW DATABASES;\""
      timeout: 20s
      retries: 5

  user-service:
    build:
      context: .
    image: uservice:hl
    entrypoint: /app/build/user-service
    container_name: user-service
    environment:
      - DB_HOST=proxysql
      - DB_PORT=6033
      - DB_LOGIN=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=hl
    ports:
      - 8080:8080
    depends_on:
      proxysql:
        condition: service_healthy

  delivery-service:
    build:
      context: .
    image: uservice:hl
    entrypoint: /app/build/delivery-service
    container_name: delivery-service
    environment:
      - DB_HOST=proxysql
      - DB_PORT=6033
      - DB_LOGIN=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=hl
      - SERVICE_HOST=user-service
    ports:
      - 8081:8081
    # depends_on:
    #   - user-service
volumes:
  db-node-1-data:
  db-node-2-data:
  proxysql-data:
