version: '3.3'

services:
  db-node-1:
    build:
      context: docker/mariadb
      dockerfile: Dockerfile
    container_name: db-node-1
    restart: always
    environment:
      MYSQL_DATABASE: hl
      MYSQL_USER: postgres
      MYSQL_PASSWORD: postgres
      MYSQL_ROOT_PASSWORD: postgres
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    healthcheck:
      test: "/usr/bin/mysql --user=postgres --password=postgres --execute \"SHOW DATABASES;\""
      timeout: 20s
      retries: 5
    ports:
      - 3306:3306
    volumes:
      - db-node-1-data:/var/lib/mysql

  user-service:
    build:
      context: .
    image: uservice:hl
    entrypoint: /app/build/user-service
    container_name: user-service
    environment:
      - DB_HOST=db-node-1
      - DB_PORT=3306
      - DB_LOGIN=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=hl
    ports:
      - 8080:8080
    depends_on:
      db-node-1:
        condition: service_healthy

  delivery-service:
    build:
      context: .
    image: uservice:hl
    entrypoint: /app/build/delivery-service
    container_name: delivery-service
    environment:
      - DB_HOST=db-node-1
      - DB_PORT=3306
      - DB_LOGIN=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=hl
      - SERVICE_HOST=user-service
    ports:
      - 8081:8081
    depends_on:
      - user-service
volumes:
  db-node-1-data:
