openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Arch Lab Example API'
  description: Пример API для первого домашнего задания по курсу Архитектура программных систем
servers:
  - url: http://localhost:8080
    description: Example server
paths:
  /api/users/search:
    get:
      summary: Поиск пользователей по маске имени и фамилии
      parameters:
      - name: first_name
        description: Имя
        in: query
        required: true
        schema:
          type: string
      - name: last_name
        description: Фамилия
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: The users for the provided masks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/users'
        404:
          description: No user found for the provided mask
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/users/self:
    get:
      summary: Проверка аутентификации
      responses:
        '200':
          description: User ID
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/user'
        401:
          description: Not authentication
  /api/users:
    get:
      summary: Чтение информации о пользователе
      parameters:
      - name: id
        description: Уникальный идентификатор пользователя
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/user_id'
      responses:
        '200':
          description: Найденный пользователь
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        404:
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Добавление нового пользователя
      parameters:
      - name: first_name
        description: Имя пользователя
        in: query
        required: true
        schema:
          type: string
      - name: last_name
        description: Фамилия пользователя
        in: query
        required: true
        schema:
          type: string
      - name: email
        description: email пользователя
        in: query
        required: true
        schema:
          type: string
      - name: title
        description: Форма обращение к пользователя 
        in: query
        required: true
        schema:
          type: string
      - name: login
        description: login пользователя
        in: query
        required: true
        schema:
          type: string
      - name: password
        description: пароль пользователя
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Идентификатор, добавленного пользователя
          content:
            application/json:
              schema:
                type: integer
        404:
          description: Ошибка добавления пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'



  /api/products:
    post:
      summary: Создание товара (посылки)
      requestBody:
        description: "Описание посылки"
        content:
          application/json:
            schema:
              type: object
              required:
                - ownerId
                - name
              properties:
                ownerId:
                  description: "Идентификатор владельца"
                  $ref: '#/components/schemas/user_id'
                name:
                  description: "Название посылки"
                  type: string
      responses:
        '200':
          description: "Созданная посылка"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/product"
        '500':
          description: Неожиданная ошибка
    get:
      summary: Получение посылок
      parameters:
      - name: ownerId
        description: Идентификатор пользователя
        in: query
        required: false
        schema:
          $ref: '#/components/schemas/user_id'
      responses:
        '200':
          description: Список посылок
          content:
            application/json:
              schema:
                $ref:  '#/components/schemas/products'
        '500':
          description: Неожиданная ошибка



  /api/deliveries:
    post:
      summary: Создание доставки
      requestBody:
        description: "Описание посылки"
        content:
          application/json:
            schema:
              type: object
              required:
                - senderId
                - recieverId
                - productId
              properties:
                senderId:
                  description: "Идентификатор отправителя"
                  $ref: '#/components/schemas/user_id'
                recieverId:
                  description: "Идентификатор получателя"
                  $ref: '#/components/schemas/user_id'
                productId:
                  description: "Идентификатор посылки"
                  $ref: "#/components/schemas/product_id"
      responses:
        '200':
          description: "Созданная доставка"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/delivery"
        '500':
          description: Неожиданная ошибка
    get:
      summary: Получение посылок
      parameters:
      - name: senderId
        description: Идентификатор отправителя
        in: query
        required: false
        schema:
          $ref: '#/components/schemas/user_id'
      - name: recieverId
        description: Идентификатор получателя
        in: query
        required: false
        schema:
          $ref: '#/components/schemas/user_id'
      responses:
        '200':
          description: Список доставок
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/deliveries"
        '500':
          description: Неожиданная ошибка



components:
  schemas:
    user_id:
      description: Уникальный идентификатор пользователя
      type: integer
    users:
      type: array
      items:
        $ref: '#/components/schemas/user'
    user:
      type: object
      required:
        - id
        - first_name
        - last_name
        - email
        - title
        - login
        - password
      properties:
        id:
          $ref: '#/components/schemas/user_id'
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        title:
          type: string
        login:
          type: string
        password:
          type: string

    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: Сообщение о ошибке
          type: string

    product_id:
      description: Уникальный идентификатор продукта (посылки)
      type: integer
    product:
      type: object
      required:
        - id
        - ownerId
        - name
      properties:
        id:
          $ref: '#/components/schemas/product_id'
        ownerId:
          $ref: '#/components/schemas/user_id'
        name:
          type: string
    products:
        type: array
        items:
          $ref: '#/components/schemas/product'

    delivery_id:
      description: Уникальный идентификатор доставки
      type: integer
    delivery:
      type: object
      required:
        - id
        - senderId
        - recieverId
        - productId
      properties:
        id:
          $ref: '#/components/schemas/delivery_id'
        senderId:
          $ref: '#/components/schemas/user_id'
        recieverId:
          $ref: '#/components/schemas/user_id'
        productId:
          $ref: '#/components/schemas/user_id'
    deliveries:
        type: array
        items:
          $ref: '#/components/schemas/delivery'

  securitySchemes:
      basicAuth:     
        type: http
        scheme: basic
security:
  - basicAuth: []